[package]
name = "binsync"
version = "0.1.0"
authors = ["Caleb Hattingh <caleb.hattingh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.8", features = ["blocking"] }
scraper = "0.12.0"
select = "0.5.0"
nipper = "0.1.8"
regex = "1.3.9"
fstrings = "0.2.3"
structopt = { version = "0.3.17", features = ["paw"] }
paw = "1.0.0"
ini = "1.3.0"
zip = "0.5.6"
compression = "0.1.5"
flate2 = "1.0.17"
tar = "0.4.30"
